In [1]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [3]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [4]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [5]:
np.random.rand()
np.random.rand(30, 4)

array([[5.23078770e-01, 2.95011566e-01, 1.66326887e-01, 1.85897822e-01],
       [9.62859930e-01, 4.17166565e-01, 3.68885705e-01, 2.76547526e-01],
       [6.14091056e-01, 9.65669244e-01, 6.26665378e-02, 2.33826387e-01],
       [4.24716414e-01, 2.82086932e-01, 6.24005107e-01, 6.40457961e-01],
       [7.15278386e-01, 4.92621166e-01, 9.34420119e-01, 2.88073868e-01],
       [6.31098224e-01, 5.10766828e-01, 5.19550155e-01, 8.27038792e-01],
       [2.74209346e-01, 4.45051824e-01, 3.58241573e-01, 7.07808915e-01],
       [2.33517094e-01, 5.10324788e-01, 8.88686494e-02, 3.55758134e-01],
       [7.75575856e-01, 5.20459512e-01, 5.19310339e-01, 5.22282916e-01],
       [9.04402484e-01, 5.74656957e-01, 4.36740245e-01, 8.19527248e-01],
       [6.99017634e-01, 1.66990899e-01, 3.15118209e-01, 8.18768425e-01],
       [1.92055989e-01, 3.68384396e-01, 7.08817879e-02, 5.27859593e-01],
       [1.28812863e-01, 4.99341477e-01, 1.04643736e-01, 8.01602013e-01],
       [9.06898121e-01, 4.32083382e-01, 5.09423649e

In [6]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 85,  83,  80,  50,  72],
       [ 57,  85,  54,  57,  98],
       [100,  60,  57,  92,  82],
       [ 92,  95,  82,  59,  94],
       [ 59,  50,  96,  62,  67],
       [ 78,  64,  52,  96,  60],
       [ 97,  66,  92,  70,  53],
       [100,  59,  79,  61,  56],
       [ 72,  99,  96,  76,  69],
       [ 81,  97,  77,  58,  71],
       [ 54,  92,  97,  86,  83],
       [ 59,  88,  85,  91,  97],
       [ 67,  98,  57,  58,  69],
       [ 98,  81,  78,  91,  85],
       [ 74,  74,  80,  89,  68],
       [ 78,  82,  95,  67,  95],
       [ 69,  95,  64, 100,  93],
       [ 72,  86,  51,  97,  54],
       [ 71,  60,  97,  88,  56],
       [ 91,  62,  98,  70,  73],
       [ 74,  57,  72, 100,  68],
       [ 77,  88,  96,  98,  89],
       [100,  51,  94,  96,  61],
       [ 86,  97,  63,  99,  56],
       [ 76,  82,  53,  73,  77],
       [ 68,  90,  64,  51,  60],
       [ 70,  97,  53,  90,  63],
       [ 99,  94,  55,  77,  88],
       [ 61,  79,  77,  82,  98],
       [ 82,  