In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [3]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 60,  93,  56,  55,  77],
       [ 72,  61,  97,  80,  56],
       [ 85,  61,  92, 100,  63],
       [ 94,  66,  90,  68,  81],
       [ 61,  64,  85,  50,  68],
       [ 90,  78,  58,  94,  94],
       [ 99,  76,  78,  75,  63],
       [ 82,  56,  59,  56,  68],
       [ 59,  53,  86,  99,  75],
       [ 99,  57,  68,  66,  74],
       [ 83,  76,  58,  64,  90],
       [ 61,  69,  98,  70,  59],
       [ 53,  86,  93,  80,  78],
       [ 92,  71,  79,  50,  55],
       [ 84,  91,  89,  68,  89],
       [ 80,  55,  65,  66,  87],
       [ 67,  52,  76,  70,  96],
       [ 61,  85,  62,  73,  53],
       [ 53,  54,  87,  52,  61],
       [ 77,  93,  65,  62,  87],
       [ 60,  91,  65,  57,  98],
       [ 89,  71,  78,  75,  84],
       [ 82,  77,  96,  70,  55],
       [ 77,  98,  64,  82,  75],
       [ 57,  79,  54,  64,  80],
       [ 56,  72,  85,  67,  84],
       [ 82,  81,  77,  72,  69],
       [ 84,  98,  76,  54,  82],
       [ 65,  69,  53,  98,  88],
       [ 73,  

In [4]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[60, 93, 56, 55, 77]], dtype=int32)

In [5]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[60, 93, 56],
       [72, 61, 97],
       [85, 61, 92],
       [94, 66, 90],
       [61, 64, 85]], dtype=int32)

In [6]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 56,  97,  92,  90,  85,  58,  78,  59,  86,  68,  58,  98,  93,
        79,  89,  65,  76,  62,  87,  65,  65,  78,  96,  64,  54,  85,
        77,  76,  53,  54,  84,  52,  94,  67,  94,  86,  55,  68,  68,
        87,  88,  50,  91, 100,  81,  63,  70,  90,  50,  99], dtype=int32)

In [7]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([341, 366, 401, 399, 328, 414, 391, 321, 372, 364, 371, 357, 390,
       347, 421, 353, 361, 334, 307, 384, 371, 397, 380, 396, 334, 364,
       381, 394, 373, 384, 375, 348, 384, 382, 420, 391, 312, 413, 424,
       404, 404, 332, 435, 420, 373, 359, 398, 382, 420, 406], dtype=int32)

In [8]:
total / 5

array([68.2, 73.2, 80.2, 79.8, 65.6, 82.8, 78.2, 64.2, 74.4, 72.8, 74.2,
       71.4, 78. , 69.4, 84.2, 70.6, 72.2, 66.8, 61.4, 76.8, 74.2, 79.4,
       76. , 79.2, 66.8, 72.8, 76.2, 78.8, 74.6, 76.8, 75. , 69.6, 76.8,
       76.4, 84. , 78.2, 62.4, 82.6, 84.8, 80.8, 80.8, 66.4, 87. , 84. ,
       74.6, 71.8, 79.6, 76.4, 84. , 81.2])

In [9]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)


array([68.2, 73.2, 80.2, 79.8, 65.6, 82.8, 78.2, 64.2, 74.4, 72.8, 74.2,
       71.4, 78. , 69.4, 84.2, 70.6, 72.2, 66.8, 61.4, 76.8, 74.2, 79.4,
       76. , 79.2, 66.8, 72.8, 76.2, 78.8, 74.6, 76.8, 75. , 69.6, 76.8,
       76.4, 84. , 78.2, 62.4, 82.6, 84.8, 80.8, 80.8, 66.4, 87. , 84. ,
       74.6, 71.8, 79.6, 76.4, 84. , 81.2])

In [10]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([68.2, 73.2, 80.2, 79.8, 65.6, 82.8, 78.2, 64.2, 74.4, 72.8, 74.2,
       71.4, 78. , 69.4, 84.2, 70.6, 72.2, 66.8, 61.4, 76.8, 74.2, 79.4,
       76. , 79.2, 66.8, 72.8, 76.2, 78.8, 74.6, 76.8, 75. , 69.6, 76.8,
       76.4, 84. , 78.2, 62.4, 82.6, 84.8, 80.8, 80.8, 66.4, 87. , 84. ,
       74.6, 71.8, 79.6, 76.4, 84. , 81.2])